### ISSUE TITLE
Front Server 이중화 및 도메인 연결

### ISSUE THREAD

**Issue by thr13** [nhnacademy-be8-plzbuybook/bookstore-shoppingmall#14]
**설명**
Nginx를 활용한 Front Server 이중화 및 도메인 연결 아래 링크 참고
https://nhnacademy.dooray.com/share/pages/g9oke2vgTlO4K82kOhkiIQ

https://nhnacademy.dooray.com/share/pages/dxGLJhTRRpSd0rA1w16Kjw

[SSL 적용, How To Secure Nginx with Let’s Encrypt on Ubuntu 20.04](https://www.rosehosting.com/blog/how-to-secure-nginx-with-lets-encrypt-on-ubuntu-20-04/)

**Comment by jalyice** [comment]
docker 사용하지 않아도 되는건가?
프론트쪽 컨트롤러, html작성해서 띄워보기
