### ISSUE TITLE
로깅 설정2 - NHNCloud Log&Crash search 적용

### ISSUE THREAD

**Issue by thr13** [nhnacademy-be8-plzbuybook/bookstore-shoppingmall#20]
**설명**
아래 링크 활용해서 로깅 설정하기

https://logback.qos.ch/

https://www.baeldung.com/spring-boot-logging

NHNCloud Log&Crash search 적용하기 (클라우드 환경에서의 로깅)

https://www.nhncloud.com/kr/service/data-analytics/log-crash-search

**Comment by jalyice** [comment]
24/12/10 12:48 현재 NHNCloud측 문제로 아직 해결 불가능.

**Comment by kkkkimtaehyeon** [comment]
24/12/11 14:34 - 개발환경(어플리케이션 콘솔), 운영환경(Log&Crash) 적용

logback sdk 적용이 안돼서 api로 로그 수집 구현한 상태
https://www.notion.so/933dddbeb10141a086e4b53ded5d1c80
