### ISSUE TITLE
erd 설계

### ISSUE THREAD

**Issue by fkqlaus** [nhnacademy-be8-plzbuybook/bookstore-shoppingmall#40]
https://www.erdcloud.com/d/rCcTvenPrHZM3x6BA

**Comment by kkkkimtaehyeon** [comment]
12/5
리뷰, 주문, 결제, 반품, 검색 테이블 수정
데이터 타입, 제약조건 설정

**Comment by kkkkimtaehyeon** [comment]
[배송 테이블] 기존에 배송지 ID를 참조했었는데 삭제 고려해서 text로 저장

**Comment by fkqlaus** [comment]
[도서 테이블] 책 작가 관계를 중간 테이블을 넣은 다대다 관계로 수정

**Comment by yjhhh123** [comment]
[회원 테이블] 회원 가입한사람의 경우 회원 등급이 해당되는게 없으므로 회원 테이블의 회원 등급 ID null을 허용

**Comment by yjhhh123** [comment]
[멤버 테이블] 회원 등급 변경로그는 날짜로 기록되어야 순수 금액 산정일 계산에 사용될 수 있어 DATE타입으로 변경

**Comment by guksy** [comment]
[회원 포인트 테이블] 포인트 사용일과 포인트 유효기한 추가

**Comment by thr13** [comment]
쿠폰 DB를 분리할 수 있도록 설계를 변경함
[쿠폰 정책 테이블] 기존에 쿠폰테이블에 있던 속성들을 모두 통합시킴
[쿠폰 타입 테이블] 고정할인쿠폰과 비율할인쿠폰 테이블을 식별관계로 추가함
[쿠폰카테고리] 카테고리와 도서를 기준으로 쿠폰을 적용함

**Comment by thr13** [comment]
회원에 쿠폰을 N:1 구조로 연결을 변경함
[쿠폰_회원 테이블] 회원의 ID 와 쿠폰DB에 존재하는 쿠폰 정책ID 를 기준으로 조회할 수 있도록 변경함, 또한 주문할인 테이블과 쿠폰_회원 테이블을 N:1로  연결을 변경함

**Comment by yjhhh123** [comment]
[배송지 테이블] 수신자, 수신자 전화번호는 null이 가능하기때문에 null로 변경

**Comment by kkkkimtaehyeon** [comment]
[포장지 테이블] 
포장지를 포장상자로 취급
개별포장 -> 포장상자별 최대 포장개수 이내로 책 포장설정 가능
전체 주문 도서에 대해 일부만 포장하는 것은 불가능

[주문-상품-포장 테이블] 삭제

**Comment by kkkkimtaehyeon** [comment]
[배송지 정책 테이블] 테이블 추가
[주문 테이블] 주문 금액 삭제
[주문-상품 테이블] 주문상품 총 금액, 주문상품 쿠폰 할인금액 속성 추가 (성능을 위한 중복 속성 추가)

**Comment by kkkkimtaehyeon** [comment]
[쿠폰 테이블]
쿠폰정책, 회원쿠폰 소유 관계 수정
